const { chromium }=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const preview=process.argv[2]||'http://127.0.0.1:8780/';
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{let checks=0,partialTotals=0;fs.mkdirSync('work/page-layout/chart-clearance',{recursive:true});
for(const dpr of [1,2]){const context=await browser.newContext({deviceScaleFactor:dpr,serviceWorkers:'block'});await context.addInitScript(()=>localStorage.setItem('is-it-dryer-out-ui-preferences',JSON.stringify({openIndoorOnLaunch:false})));const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/api.open-meteo.com/**',r=>r.abort());await page.goto(preview);await page.waitForFunction(()=>document.querySelector('.recommendation').dataset.weatherState==='failed');
await page.evaluate(()=>{const svg=document.querySelector('#ahChart');svg.replaceWith(svg.cloneNode(true));});await page.waitForTimeout(100);
await page.evaluate(async()=>{const {createChart}=await import('./src/ui/chart.js');const {absoluteHumidity}=await import('./src/domain/humidity.js');const {buildWeatherTimeline}=await import('./src/domain/forecast.js');const start=new Date();const state={indoorTemp:24,indoorRh:58,outdoorTemp:12,outdoorRh:75,outdoorDewPoint:8,outdoorPressure:1013.25,outdoorWind:12,outdoorWindDirection:225,updatedAt:start.toISOString(),timezone:'Europe/London',chartHours:24,chartSelection:0,roomPreset:'medium',openingSetup:'single',weatherRequestPending:false,weatherLoadFailed:false,forecast:Array.from({length:50},(_,i)=>({time:new Date(Math.floor(start.getTime()/3600000)*3600000+i*3600000),temp:12,rh:75,dewPoint:8,pressure:1013.25,wind:12,windDirection:225,rainfall:i<6||i>=12&&i<19?2:0,precipitationProbability:90}))};const chart=createChart({state,formatShortTime:d=>d.toISOString().slice(11,16)});window.clearanceTest={state,chart,absoluteHumidity,buildWeatherTimeline};document.querySelector('.recommendation').className='recommendation open';});

const shared=new Map();
for(const width of [320,390,768,1280])for(const scale of [100,200])for(const hours of [24,48])for(const temp of [24,45])for(const rh of [5,34,58,99]){
await page.setViewportSize({width,height:1000});await page.evaluate(scale=>document.documentElement.style.fontSize=scale+'%',scale);await page.waitForTimeout(50);
await page.evaluate(({hours,rh,temp})=>{const {state,chart}=window.clearanceTest;state.indoorTemp=temp;state.indoorRh=rh;state.chartHours=hours;chart.renderAhChart();},{hours,rh,temp});
const result=await page.locator('#ahChart').evaluate(svg=>{const line=svg.querySelector('.ah-indoor-line'),d=line.getAttribute('d'),lineY=Number(d.match(/M[^ ]+ ([^H]+)/)[1]),pixels=svg.getBoundingClientRect().width/480;const gaps=[...svg.querySelectorAll('.ah-indoor-label,.rain-spell-total')].map(label=>{const b=label.getBBox();return {text:label.textContent,rain:label.matches('.rain-spell-total'),gap:Math.max(b.y-lineY,lineY-b.y-b.height)*pixels-.5,top:b.y,bottom:b.y+b.height};});const {state,chart,buildWeatherTimeline}=window.clearanceTest,model=chart.buildAhOutlook(buildWeatherTimeline(state),state.chartHours),{indoor,low,high:baseHigh}=model,high=low+(indoor-low)*150/(158-lineY);
const probe=document.createElementNS('http://www.w3.org/2000/svg','text');probe.setAttribute('class','rain-spell-total');probe.setAttribute('y',8+11/pixels);probe.setAttribute('visibility','hidden');probe.textContent='≥ 13.8 mm';svg.append(probe);const rain=probe.getBBox();probe.remove();const h=svg.querySelector('.ah-indoor-label').getBBox().height,rainHigh=Math.max(baseHigh,Math.ceil(low+(indoor-low)*150/(158-rain.y-rain.height-4.5/pixels))),rainY=158-(indoor-low)*150/(rainHigh-low),fits=rainY-6/pixels-h>=8+4/pixels||rainY+6/pixels+h<=158-4/pixels,expectedHigh=fits?rainHigh:Math.max(rainHigh,Math.ceil(low+(indoor-low)*150/(158-8-h-10/pixels)));
return {d,lineY,gaps,high,expectedHigh,low,indoor,baseHigh,mask:line.getAttribute('mask'),maskNodes:svg.querySelectorAll('#ahIndoorClearance').length,rainCount:svg.querySelectorAll('.rain-spell-total').length,partial:gaps.some(n=>n.text.includes('≥'))};});
assert.match(result.d,/^M0 [\d.e+-]+H480$/);assert.equal(result.mask,null);assert.equal(result.maskNodes,0);assert.ok(Math.abs(result.high-result.expectedHigh)<.000001,`Smallest bound ${width}/${scale}/${hours}/${temp}/${rh}: ${JSON.stringify(result)}`);
for(const g of result.gaps){assert.ok(g.gap>=4-.01,`${width}/${scale}/${hours}/${temp}/${rh} ${g.text} gap ${g.gap}`);assert.ok(g.top>=8-.01&&g.bottom<=158+.01);}
if(hours===48)assert.equal(result.rainCount,0);partialTotals+=Number(result.partial);
const key=[width,scale,temp,rh].join('/');if(shared.has(key))assert.ok(Math.abs(shared.get(key)-result.lineY)<.0001,'24h/48h reference height must match');else shared.set(key,result.lineY);
await page.evaluate(()=>window.clearanceTest.chart.renderAhChart());assert.equal(await page.locator('#ahChart .ah-indoor-line').getAttribute('d'),result.d,'No accumulated padding');
await page.locator('#ahChart').focus();await page.keyboard.press('Home');const before=await page.locator('#ahChart').getAttribute('aria-valuenow');await page.keyboard.press('ArrowRight');assert.notEqual(await page.locator('#ahChart').getAttribute('aria-valuenow'),before);const b=await page.locator('#ahChart').boundingBox();await page.locator('#ahChart').click({position:{x:b.width*.5,y:b.height*.5}});assert.ok(Number(await page.locator('#ahChart').getAttribute('aria-valuenow'))>0);
if(temp===45&&rh===34)await page.locator('#ahChart').screenshot({path:`work/page-layout/chart-clearance/headroom-${width}-${scale}-${dpr}-${hours}.png`});checks++;
}
// Fractional rising/falling readings revisit exactly the same base bounds.
const sequence=await page.evaluate(()=>{const {state,chart}=window.clearanceTest;state.indoorTemp=45;state.chartHours=24;return [34,34.25,34.5,34.75,35,34].map(rh=>{state.indoorRh=rh;chart.renderAhChart();return document.querySelector('.ah-indoor-line').getAttribute('d');});});assert.equal(sequence[0],sequence.at(-1));
await page.evaluate(()=>{const {state,chart}=window.clearanceTest;state.forecast.forEach(n=>n.rainfall=0);chart.renderAhChart();});assert.equal(await page.locator('#ahChart .rain-spell-total').count(),0);
for(const mode of ['loading','failed','ready']){await page.evaluate(mode=>{const {state,chart}=window.clearanceTest;state.weatherRequestPending=mode==='loading';state.weatherLoadFailed=mode==='failed';chart.renderAhChart();},mode);assert.equal(await page.locator('#ahChart').getAttribute('data-weather-state'),mode);assert.equal(await page.locator('#ahChart .ah-indoor-line').getAttribute('mask'),null);assert.ok(await page.locator('#ahChart').evaluate(svg=>{const b=svg.querySelector('.ah-indoor-label').getBBox(),y=Number(svg.querySelector('.ah-indoor-line').getAttribute('d').match(/M[^ ]+ ([^H]+)/)[1]);return Math.max(b.y-y,y-b.y-b.height)*svg.getBoundingClientRect().width/480-.5>=3.99;}));}
assert.deepEqual(errors,[]);await context.close();}
assert.ok(partialTotals>0,'Partial rain totals were tested');console.log(`PASS ${checks} continuous-line chart layouts: 4px text clearance, shared ranges, broad/narrow AH, repeat rendering, inspection and weather transitions.`);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
