const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const url=process.argv[2]||'http://127.0.0.1:8780/';
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{let checks=0;fs.mkdirSync('work/page-layout/dividers',{recursive:true});
for(const dpr of [1,2]){const context=await browser.newContext({deviceScaleFactor:dpr,serviceWorkers:'block'});await context.addInitScript(()=>localStorage.setItem('is-it-dryer-out-ui-preferences',JSON.stringify({openIndoorOnLaunch:false})));const page=await context.newPage();await page.route('**/api.open-meteo.com/**',r=>r.abort());await page.goto(url);
for(const width of [320,390,768,1280])for(const scale of [100,200])for(const count of [0,1,3,5])for(const long of [false,true]){
await page.setViewportSize({width,height:1400});await page.evaluate(({scale,count,long})=>{document.documentElement.style.fontSize=scale+'%';document.querySelector('.recommendation-explainer').open=true;document.querySelector('#explanationStatus').hidden=true;const host=document.querySelector('#explanationOverview');host.hidden=false;host.replaceChildren();for(let i=0;i<count;i++){const p=document.createElement('p'),icon=document.createElement('span'),copy=document.createElement('span'),label=document.createElement('strong'),text=document.createElement('span');copy.className='explanation-copy';label.textContent=['Small benefit','Rain','Wind','Cooling','Longer time'][i];text.textContent=long?'Little noticeable improvement is expected. The room may lose moisture while cooling keeps the humidity reading high.':'A brief opening for fresh air may not lower humidity.';copy.append(label,text);p.append(icon,copy);host.append(p);}}, {scale,count,long});
const result=await page.locator('#explanationOverview').evaluate(host=>[...host.children].map(n=>{const s=getComputedStyle(n,'::before'),r=n.getBoundingClientRect();return {line:s.content!=='none',height:s.height,width:s.borderTopWidth,background:s.backgroundColor,border:getComputedStyle(n).borderTopWidth,offset:s.top,gap:n.previousElementSibling?r.top-n.previousElementSibling.getBoundingClientRect().bottom:null};}));
assert.equal(result.filter(r=>r.line).length,Math.max(0,count-1));for(const [i,row]of result.entries()){assert.equal(row.border,'0px');if(i){assert.equal(row.height,'0px');assert.equal(row.width,'1px');assert.equal(row.background,'rgba(0, 0, 0, 0)');assert.equal(row.offset,'-8px');assert.ok(Math.abs(row.gap-16)<.1);}}
if(count===3)await page.locator('.recommendation-explainer').screenshot({path:`work/page-layout/dividers/${width}-${dpr}-${scale}-${long}.png`});checks++;
}await context.close();}console.log(`PASS ${checks} divider configurations: zero/single/multiple entries, text changes, widths, text sizes and display scales.`);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
