const { chromium }=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const preview=process.argv[2]||'http://127.0.0.1:8780/', artifacts=path.resolve('work/page-layout/sheets');fs.mkdirSync(artifacts,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})});try{
const context=await browser.newContext({serviceWorkers:'block',userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'});await context.addInitScript(()=>localStorage.setItem('is-it-dryer-out-ui-preferences',JSON.stringify({openIndoorOnLaunch:false})));
await context.route('**/api.open-meteo.com/**',route=>{const start=Math.floor(Date.now()/3600000)*3600,time=Array.from({length:50},(_,i)=>start+i*3600),repeat=v=>time.map(()=>v);return route.fulfill({json:{timezone:'Europe/London',current:{time:start,temperature_2m:12,relative_humidity_2m:70,surface_pressure:1013,wind_speed_10m:9},hourly:{time,temperature_2m:repeat(12),relative_humidity_2m:repeat(70),surface_pressure:repeat(1013),wind_speed_10m:repeat(9),wind_direction_10m:repeat(90),rain:repeat(0),showers:repeat(0),precipitation_probability:repeat(0)}}});});
const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(preview);await page.waitForFunction(()=>document.querySelector('.recommendation').dataset.weatherState==='ready');
const cases=[['settings','settingsDialog','settingsButton'],['manual','indoorDialog','editIndoorButton'],['ventilation','planDialog','planSummaryButton'],['location','locationDialog','locationButton'],['timer','timerDialog','.verdict-time'],['timer-help','timerDialog','.verdict-time'],['location-pending','locationDialog','locationButton'],['location-error','locationDialog','locationButton'],...['listening','review','error'].map(v=>['voice-'+v,'indoorDialog','editIndoorButton']),...['loading','capture','review','error','help'].map(v=>['camera-'+v,'indoorDialog','editIndoorButton'])];let checks=0;
for(const width of [320,390,768,1280])for(const scale of [100,200]){await page.setViewportSize({width,height:900});await page.evaluate(v=>document.documentElement.style.fontSize=v+'%',scale);
for(const [name,id,opener]of cases){await page.locator(opener.startsWith('.')?opener:'#'+opener).first().click();
await page.evaluate(name=>{if(name.startsWith('location-'))document.querySelector('#locationDialogStatus').textContent=name==='location-pending'?'Searching…':'Search could not be completed. Try again.';const indoor=document.querySelector('#indoorDialog');if(name.startsWith('voice-')){indoor.classList.add('voice-mode');document.querySelector('#voiceDialog').hidden=false;document.querySelector('#voiceStatus').textContent=name==='voice-listening'?'Listening…':name==='voice-review'?'Review your readings':'Microphone is unavailable.';document.querySelector('#voiceStatus').classList.toggle('is-listening',name==='voice-listening');}
if(name.startsWith('camera-')){indoor.classList.add('camera-mode');document.querySelector('#cameraPanel').hidden=false;for(const view of ['Capture','Review','Error'])document.querySelector('#camera'+view+'Panel').hidden=!(name==='camera-'+view.toLowerCase()||(view==='Capture'&&(name==='camera-loading'||name==='camera-help')));document.querySelector('#indoor-heading').textContent=name==='camera-review'?'Review readings':'Camera';document.querySelector('#cameraBackButton').hidden=false;document.querySelector('#cameraHelpButton').hidden=name==='camera-error';document.querySelector('#cameraErrorMessage').textContent='The camera is unavailable. Try again or enter readings manually.';document.querySelector('#cameraCaptureStatus').textContent=name==='camera-loading'?'Starting camera…':'Ready to take a photo.';}},name);
await page.waitForFunction(id=>Math.abs(parseFloat(document.querySelector('#'+id).style.getPropertyValue('--sheet-header-height'))-document.querySelector('#'+id+' .sheet-header').getBoundingClientRect().height)<.1,id);
const geometry=await page.locator('#'+id).evaluate(node=>{const box=n=>n.getBoundingClientRect(),style=n=>getComputedStyle(n),header=node.querySelector('.sheet-header'),row=header.querySelector('.sheet-title-row'),body=node.querySelector('.sheet-body');
const visible=Array.from(body.children).find(n=>n.getClientRects().length&&style(n).display!=='none');return {gap:box(visible).top-box(row).bottom,padding:style(header).paddingLeft,right:style(header).paddingRight,rowGap:style(row).gap,rowHeight:box(row).height,handleHeight:box(header.querySelector('.sheet-handle')).height,headerHeight:box(header).height,scrollPadding:parseFloat(style(node).scrollPaddingTop),overflow:node.scrollWidth>node.clientWidth+1,gradient:style(header).backgroundImage};});
assert.ok(Math.abs(geometry.gap-16)<.1,`${name}/${width}/${scale} content gap ${geometry.gap}`);assert.equal(geometry.padding,'20px');assert.equal(geometry.right,'20px');assert.equal(geometry.rowGap,'8px');assert.ok(geometry.rowHeight>=44);assert.equal(geometry.handleHeight,width<640?36:0);assert.ok(Math.abs(geometry.headerHeight-geometry.scrollPadding)<.1);assert.equal(geometry.overflow,false,`${name}/${width}/${scale} overflow`);assert.match(geometry.gradient,/linear-gradient/);
if(name==='camera-capture'||name==='camera-help'){
const readable=await page.locator('#'+id).evaluate(n=>{const title=n.querySelector('h2'),back=n.querySelector('#cameraBackButton'),b=title.getBoundingClientRect(),range=document.createRange();range.selectNodeContents(title);return {lines:range.getClientRects().length,titleBottom:b.bottom,backTop:back.getBoundingClientRect().top};});
assert.equal(readable.lines,1,`${name}/${width}/${scale} Camera must remain a whole word`);
if(width===320&&scale===200)assert.ok(readable.backTop>=readable.titleBottom,`${name} Back must wrap below Camera`);
}
if(name==='timer-help'||name==='camera-help'){
const selector=name==='timer-help'?'#timerHelp > summary':'#cameraHelpButton';await page.locator(selector).click();
if(name==='camera-help')await page.evaluate(()=>{document.querySelector('#cameraCropHint').hidden=false;document.querySelector('#cameraHelpButton').setAttribute('aria-expanded','true');document.querySelector('#cameraCaptureHint').hidden=false;document.querySelector('#cameraReviewHint').hidden=true;});
const help=await page.locator(name==='timer-help'?'.timer-help-content':'.camera-help-content').evaluate(n=>{const b=n.getBoundingClientRect();return {left:b.left,right:b.right,top:b.top,bottom:b.bottom,overflow:getComputedStyle(n).overflowY,dragAncestor:!!n.closest('.sheet-drag-surface')};});
assert.equal(await page.locator(name==='timer-help'?'.timer-help-content':'.camera-help-content').isVisible(),true);assert.ok(help.right>help.left&&help.bottom>help.top&&help.left>=0&&help.right<=width+1&&help.top>=0&&help.bottom<=900+1,`${name} help bounds ${JSON.stringify(help)}`);assert.equal(help.overflow,'auto');assert.equal(help.dragAncestor,false);
}
await page.locator('#'+id).evaluate(n=>n.scrollTop=n.scrollHeight);const pinned=await page.locator('#'+id).evaluate(n=>({top:n.querySelector('.sheet-header').getBoundingClientRect().top,border:n.getBoundingClientRect().top+n.clientTop}));assert.ok(Math.abs(pinned.top-pinned.border)<1,`${name} pinned`);
await page.locator('#'+id).screenshot({path:path.join(artifacts,`${name}-${width}-${scale}.png`)});
await page.evaluate(id=>{const n=document.querySelector('#'+id);n.classList.remove('voice-mode','camera-mode');document.querySelector('#voiceDialog').hidden=true;document.querySelector('#cameraPanel').hidden=true;document.querySelector('#cameraBackButton').hidden=true;document.querySelector('#cameraHelpButton').hidden=true;document.querySelector('#cameraCropHint').hidden=true;document.querySelector('#cameraHelpButton').setAttribute('aria-expanded','false');document.querySelector('#indoor-heading').textContent='Indoor readings';n.close();},id);checks++;}}
for(const id of ['indoorDialog','planDialog','locationDialog','settingsDialog','timerDialog']){
await page.setViewportSize({width:390,height:568});await page.evaluate(()=>document.documentElement.style.fontSize='200%');
const opener=cases.find(c=>c[1]===id)[2];await page.locator(opener.startsWith('.')?opener:'#'+opener).first().click();
await page.evaluate(()=>{Object.defineProperty(visualViewport,'height',{configurable:true,value:350});Object.defineProperty(visualViewport,'offsetTop',{configurable:true,value:50});visualViewport.dispatchEvent(new Event('resize'));});
await page.waitForFunction(()=>parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--sheet-visible-height'))===350);
const keyboard=await page.locator('#'+id).evaluate(n=>{const b=n.getBoundingClientRect();return{top:b.top,bottom:b.bottom,max:parseFloat(getComputedStyle(n).maxHeight)};});assert.ok(keyboard.top>=65&&keyboard.bottom<=400+1&&Math.abs(keyboard.max-334)<1,`${id} keyboard bounds ${JSON.stringify(keyboard)}`);
const input={indoorDialog:'#indoorTempInput',planDialog:'#minTempInput',locationDialog:'#locationSearchInput',settingsDialog:'#showVoiceButton',timerDialog:'#timerMinutesInput'}[id];
await page.locator(input).focus();await page.locator(input).scrollIntoViewIfNeeded();
const focusBox=await page.locator(input).evaluate(n=>({top:n.getBoundingClientRect().top,bottom:n.getBoundingClientRect().bottom,header:n.closest('dialog').querySelector('.sheet-header').getBoundingClientRect().bottom}));
assert.ok(focusBox.top>=focusBox.header-.1&&focusBox.bottom<=400+1,`${id} keyboard focus ${JSON.stringify(focusBox)}`);
await page.locator('#'+id).screenshot({path:path.join(artifacts,`${id}-keyboard.png`)});
await page.evaluate(id=>{delete visualViewport.height;delete visualViewport.offsetTop;visualViewport.dispatchEvent(new Event('resize'));document.querySelector('#'+id).close();},id);
}
const board=await context.newPage();await board.goto(preview+'docs/design-system.html#sheet-headers');
assert.equal(await board.locator('.board-sheet').count(),7);await board.locator('#sheet-headers').screenshot({path:path.join(artifacts,'design-system-sheet-headers.png')});
assert.deepEqual(errors,[]);console.log(`PASS ${checks} sheet/mode layouts: header gaps, fade, wrapping, measured focus padding, sticky placement and overflow.`);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
