const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');
const preview=process.argv[2]||'http://127.0.0.1:8780/';const artifacts=path.resolve('work/page-layout/supporting');fs.mkdirSync(artifacts,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})});try{
const context=await browser.newContext({serviceWorkers:'block'});await context.addInitScript(()=>{if(!localStorage.getItem('is-it-dryer-out-ui-preferences'))localStorage.setItem('is-it-dryer-out-ui-preferences',JSON.stringify({openIndoorOnLaunch:false}));});
let mode='success',release;const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await context.route('**/api.open-meteo.com/**',async route=>{if(mode==='pending')await new Promise(resolve=>release=resolve);if(mode==='failed')return route.fulfill({status:500,body:'failed'});
const start=Math.floor(Date.now()/3600000)*3600,time=Array.from({length:50},(_,i)=>start+i*3600),repeat=value=>time.map(()=>value);
await route.fulfill({json:{timezone:'Europe/London',current:{time:start,temperature_2m:12,relative_humidity_2m:75,dew_point_2m:7.7,surface_pressure:1013.25,wind_speed_10m:12,wind_direction_10m:225},hourly:{time,temperature_2m:repeat(12),relative_humidity_2m:repeat(75),dew_point_2m:repeat(7.7),surface_pressure:repeat(1013.25),wind_speed_10m:repeat(12),wind_direction_10m:repeat(225),rain:repeat(1),showers:repeat(0),precipitation_probability:repeat(60)}}});});
await page.goto(preview);await page.waitForFunction(()=>document.querySelector('.recommendation').dataset.weatherState==='ready');
for(const selector of ['#chartKey > summary','.glossary-explainer > summary','.weather-data-explainer > summary','.forecast-explainer > summary','#explanationDetailsSummary'])await page.locator(selector).click();
let checks=0;for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:900});for(const scale of [100,200]){
await page.evaluate(scale=>{document.documentElement.style.fontSize=scale+'%';document.querySelector('#sourceLocationName').textContent='Llanfairpwllgwyngyll, Isle of Anglesey, United Kingdom';},scale);
const geometry=await page.evaluate(()=>{const box=node=>node.getBoundingClientRect(),style=node=>getComputedStyle(node),meta=document.querySelector('.weather-metadata'),row=meta.firstElementChild,label=row.querySelector('dt'),value=row.querySelector('dd');
return{overflow:document.documentElement.scrollWidth>innerWidth+1,contentWidth:box(document.querySelector('.weather-data-explainer')).width,threshold:20*parseFloat(style(document.documentElement).fontSize),stacked:box(value).top>box(label).top+1,
links:[...document.querySelectorAll('.weather-source-details a')].map(n=>({height:box(n).height,width:box(n).width,target:n.target,underline:style(n).textDecorationLine,icon:n.querySelector('svg').getAttribute('aria-hidden')})),
glossary:document.querySelectorAll('.stacked-definitions dt').length,glossaryGaps:[...document.querySelectorAll('.stacked-definitions >div')].map(n=>box(n.querySelector('dd')).top-box(n.querySelector('dt')).bottom),
legend:[...document.querySelectorAll('.chart-key-entry')].map(n=>style(n).gridTemplateColumns),legendCount:document.querySelectorAll('.chart-key-entry').length,
labels:[...document.querySelectorAll('.explanation-detail')].map(n=>({visible:!n.hidden,text:n.querySelector('strong').textContent,paragraphHidden:n.querySelector('p').hidden})),
copy:[...document.querySelectorAll('.explanation-copy')].map(n=>({gap:box(n.children[1]).top-box(n.children[0]).bottom})),
headings:[...document.querySelectorAll('.dashboard-explainer > summary')].map(n=>({size:parseFloat(style(n).fontSize),weight:style(n).fontWeight,color:style(n).color,line:parseFloat(style(n).lineHeight),height:box(n).height,width:box(n).width,parentWidth:box(n.parentElement).width,chevron:getComputedStyle(n,'::after').borderTopColor})),
rootSize:parseFloat(style(document.documentElement).fontSize),bodySize:parseFloat(style(document.querySelector('.explanation-copy')).fontSize),detailLabels:[...document.querySelectorAll('.explanation-detail > strong')].map(n=>({color:style(n).color,size:parseFloat(style(n).fontSize)})),secondary:{size:parseFloat(style(document.querySelector('#explanationDetailsSummary')).fontSize),weight:style(document.querySelector('#explanationDetailsSummary')).fontWeight,underline:style(document.querySelector('#explanationDetailsSummary')).textDecorationLine},
metadataTerms:[...meta.querySelectorAll('dt')].map(n=>n.textContent)};});
assert.equal(geometry.overflow,false,`${width}/${scale} overflow`);assert.equal(geometry.stacked,geometry.contentWidth<geometry.threshold);assert.equal(geometry.glossary,6);assert.equal(geometry.legendCount,7);assert.ok(geometry.legend.every(columns=>columns.startsWith('20px ')));assert.ok(geometry.glossaryGaps.every(gap=>Math.abs(gap-8)<.1));assert.ok(geometry.copy.every(x=>Math.abs(x.gap-8)<.1));assert.deepEqual(geometry.metadataTerms,['Provider','Location','Last update']);for(const link of geometry.links){assert.ok(link.height>=44&&link.width>=44);assert.equal(link.target,'_blank');assert.equal(link.underline,'underline');assert.equal(link.icon,'true');}for(const entry of geometry.labels)assert.equal(entry.visible,!entry.paragraphHidden);
assert.equal(geometry.headings.length,5);for(const heading of geometry.headings){assert.equal(heading.size,geometry.rootSize);assert.equal(heading.weight,'700');assert.equal(heading.color,'rgb(64, 60, 55)');assert.equal(heading.chevron,heading.color);assert.ok(Math.abs(heading.line-heading.size*1.4)<.1);assert.ok(heading.height>=48);assert.ok(Math.abs(heading.width-heading.parentWidth)<.1);assert.ok(heading.size>geometry.bodySize);}
for(const label of geometry.detailLabels){assert.equal(label.color,'rgb(64, 60, 55)');assert.equal(label.size,geometry.bodySize);}assert.equal(geometry.secondary.size,geometry.bodySize);assert.equal(geometry.secondary.weight,'400');assert.equal(geometry.secondary.underline,'underline');
for(const [name,selector]of Object.entries({recommendation:'.recommendation-explainer',weather:'.weather-data-explainer',glossary:'.glossary-explainer',chart:'#chartKey',estimates:'.forecast-explainer'}))await page.locator(selector).screenshot({animations:'disabled',path:path.join(artifacts,`${name}-${width}-${scale}.png`)});await page.locator('.details-footnotes').screenshot({animations:'disabled',path:path.join(artifacts,`hierarchy-open-${width}-${scale}.png`)});
for(const heading of await page.locator('.dashboard-explainer > summary').all()){await heading.focus();await page.keyboard.press('Enter');assert.equal(await heading.evaluate(n=>n.parentElement.open),false);assert.equal(await heading.evaluate(n=>getComputedStyle(n).fontWeight),'700');await heading.screenshot({animations:'disabled',path:path.join(artifacts,`heading-${(await heading.textContent()).replace(/[^a-z]/gi,'')}-${width}-${scale}.png`)});}
await page.locator('.details-footnotes').screenshot({animations:'disabled',path:path.join(artifacts,`hierarchy-closed-${width}-${scale}.png`)});
for(const heading of await page.locator('.dashboard-explainer > summary').all()){await heading.focus();await page.keyboard.press('Space');assert.equal(await heading.evaluate(n=>n.parentElement.open),true);assert.ok(await heading.evaluate(n=>n.matches(':focus-visible')));assert.equal(await heading.evaluate(n=>getComputedStyle(n,'::before').borderTopWidth),'2px');}
checks++;}}
const lastSuccess=await page.locator('#weatherDataUpdated').textContent();mode='pending';await page.locator('#refreshWeather').click();await page.waitForFunction(()=>document.querySelector('#weatherDataStatus').textContent.includes('in progress'));assert.equal(await page.locator('#weatherDataUpdated').textContent(),lastSuccess);assert.equal(await page.locator('#explanationDetails').isVisible(),false);assert.equal(await page.locator('#explanationDetails').evaluate(n=>n.open),true);mode='failed';release();await page.waitForFunction(()=>document.querySelector('#weatherDataStatus').textContent.includes('failed'));assert.equal(await page.locator('#weatherDataUpdated').textContent(),lastSuccess);mode='success';await page.locator('#refreshWeather').click();await page.waitForFunction(()=>document.querySelector('.recommendation').dataset.weatherState==='ready');assert.equal(await page.locator('#weatherDataStatus').isVisible(),false);assert.equal(await page.locator('#explanationDetails').evaluate(n=>n.open),true);
await page.locator('.weather-source-details a').first().focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');assert.ok(await page.locator('.weather-source-details a').first().evaluate(n=>getComputedStyle(n).outlineWidth==='2px'));
mode='failed';const firstLoad=await context.newPage();await firstLoad.goto(preview);await firstLoad.waitForFunction(()=>document.querySelector('.recommendation').dataset.weatherState==='failed');assert.equal(await firstLoad.locator('#weatherDataUpdated').textContent(),'Not available yet');assert.match(await firstLoad.locator('#weatherDataStatus').textContent(),/No successful/);mode='success';await firstLoad.locator('#refreshWeather').click();await firstLoad.waitForFunction(()=>document.querySelector('.recommendation').dataset.weatherState==='ready');assert.notEqual(await firstLoad.locator('#weatherDataUpdated').textContent(),'Not available yet');await firstLoad.close();await page.locator('#chartKey > summary').click();await page.reload();await page.waitForFunction(()=>document.querySelector('.recommendation').dataset.weatherState==='ready');assert.equal(await page.locator('#chartKey').evaluate(n=>n.open),false);assert.equal(await page.locator('#explanationDetails').evaluate(n=>n.open),false);
assert.deepEqual(errors,[]);const board=await context.newPage();await board.goto(preview+'docs/design-system.html#foundations');await board.screenshot({fullPage:true,path:path.join(artifacts,'design-system.png')});for(const [i,specimen]of (await board.locator('.board-detail').all()).entries())await specimen.screenshot({path:path.join(artifacts,`board-pattern-${i+1}.png`)});for(const heading of await board.locator('.board-hierarchy .dashboard-explainer > summary').all()){if(!await heading.evaluate(n=>n.parentElement.open))await heading.click();}await board.locator('.board-hierarchy').screenshot({path:path.join(artifacts,'board-hierarchy.png')});assert.equal(await board.locator('.board-hierarchy .dashboard-explainer').count(),5);console.log(`PASS ${checks} responsive supporting-detail views, metadata refresh/failure/recovery, link targets/focus, semantics, legend and label spacing.`);
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1});
